---
title: "Assignment"
author: "Priscilla Hare and Callie Steffen"
date: "5/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load the libraries into this R session
library(raster)       #Main raster library with nearly all functions used in this analysis
library(rgdal)        #Spatial library - most functions used from rgdal are for vectors (shapefiles)
library(rasterVis)    #Useful for raster visualizations
library(maps)         #Has a database of maps. I use this to add a map to my raster to visualize land boundaries
library(rgeos)        #Need this library for topology operations on geometries
library(dplyr)        #NOT spatial - this is a data wrangling library
library(RColorBrewer) #Also not spatial - used to set the spectral color scheme 
```

```{r}
# rainbow color scheme
cols = rev(colorRampPalette(brewer.pal(11, 'Spectral'))(255)) 

#setting smaller margins for plotting
par(mar=c(2,2,1,1))
```


Load threat layers for climate: acid, sst, uv
```{r}

acid <- raster("Threats_data/impact_acid.tif")
plot(acid, col = cols)

sst <- raster("Threats_data/impact_sst.tif")
plot(sst, col = cols)

uv <- raster("Threats_data/impact_uv.tif")
plot(uv, col = cols)


```
stack climate layers
```{r}
climate_stack <- stack(acid, sst, uv)
plot(climate_stack, col = cols)
#resolution and extents already the same
```
reclassify zeroes as NAs if needed
```{r}
hist(acid)
acid <- reclassify(acid, rcl = c(-Inf, 0, NA))
plot(acid)

hist(sst)
#sst_test <- reclassify(sst, rcl = c(-Inf, 0 , NA))
sst_masked <- mask(sst, acid) #mask sst layer to shape of reclassified acid layer (removes NAs coded as 0 and keep real 0s)
plot(sst_masked)

hist(uv)
uv <- reclassify(uv, rcl = c(-Inf, 0, NA))
plot(uv)

```

Still to come....
-reclassify top 20%
-overlay climate threats

and then....
-overlay climate threats with species to get hotspots (in this will need to check extent and resolution)
